// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUZ88k3si6sSrHYZW9T-RP3zdHmnCOiU',
    appId: '1:571740178087:web:3cba893fb5599a063d3d82',
    messagingSenderId: '571740178087',
    projectId: 'pet-app-phalanx-1',
    authDomain: 'pet-app-phalanx-1.firebaseapp.com',
    storageBucket: 'pet-app-phalanx-1.appspot.com',
    measurementId: 'G-K0KRT5PX6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2yDNemWszYByvoG1s7btAVXwy9L8QsLo',
    appId: '1:571740178087:android:76bd6fd61ab049bb3d3d82',
    messagingSenderId: '571740178087',
    projectId: 'pet-app-phalanx-1',
    storageBucket: 'pet-app-phalanx-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCteHI6kUFK6qJAVYLNeyKdQHuo5JZbjrw',
    appId: '1:571740178087:ios:03aea4019d9d71663d3d82',
    messagingSenderId: '571740178087',
    projectId: 'pet-app-phalanx-1',
    storageBucket: 'pet-app-phalanx-1.appspot.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCteHI6kUFK6qJAVYLNeyKdQHuo5JZbjrw',
    appId: '1:571740178087:ios:1f243e6db74a31183d3d82',
    messagingSenderId: '571740178087',
    projectId: 'pet-app-phalanx-1',
    storageBucket: 'pet-app-phalanx-1.appspot.com',
    iosBundleId: 'com.example.petApp.RunnerTests',
  );
}
